### PR TITLE
Documentation Refactoring

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Separator]: https://raw.githubusercontent.com/ElectronicsArchiver/ElectronicsArchiver/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB/Separator.png

[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｃｏｍｍｅｎｄａｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<div align = center>

![Separator]

<br>
<br>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

<br>
<br>

## ![Badge Changes]

- Complete documentation rework

- Rewrote everything in markdown

- General formatting / spacing

- Split mails into separate files

- Added quicklinkks

- Linked contributors in credits
  ( as far as I could find them )

- Adjusted Makefile paths

- Merged versions & changes

<br>
<br>

<div align = center>

![Separator]

</div>

[Preview]: https://github.com/ElectronicsArchiver/cron

### CODE REVIEW

**Comment by vixie** [comment]
is this ready for review?

**Comment by ElectronicsArchiver** [comment]
@vixie Sorry, forgot to continue working on it, 
I'll finish it up and notify you once it's done!

**Comment by ElectronicsArchiver** [comment]
Almost done, I only have to format the installation and do some README adjustments.

**Comment by ElectronicsArchiver** [comment]
@vixie Done, well for now.

**Pull request merged**
